### ISSUE TITLE
✅ [23.02.05] 메인페이지 css 작업

### ISSUE THREAD

**Issue by baeseongjae** [phoenix-kurly/phoenix-kurly#45]
## 작업 사항
메인페이지 css 작업

## Todo
- [x] 메인 영역(상품리스트) 레이아웃 및 디자인 작업
- [x] 장바구니 팝업 디자인 작업
- [x] 최근 본 상품 사이드바 배치 및 css작업
- [x] 클래스명 수정(product-list => today-product-list)
