### ISSUE TITLE
✅ [23.02.05] header 작업 #47

### ISSUE THREAD

**Issue by Stilllee** [phoenix-kurly/phoenix-kurly#47]
## 작업 사항
> 작업 사항(구현할 내용)을 입력해주세요.
✅ 완료된 작업 사항은 제목에 완료한 이슈 번호를 입력해주세요.

## Todo
- [x] css 요소 배치
- [x] font-size, bold 등 조정
- [x] search-form 스타일 작업
- [x] category 숨김 on/off 처리
- [x] svg hover시 색상변경
- [x] navigation 스타일 변형

## 기타
> 필요한 경우 작성해주세요.
