### ISSUE TITLE
✅ [23.02.06] 회원가입 자바스크립트 

### ISSUE THREAD

**Issue by hungerbk** [phoenix-kurly/phoenix-kurly#56]
## 작업 사항
회원가입 부분  필요한 함수 작업

## Todo
- [x] 비밀번호 확인 기능 구현
- [x] 이메일 validation 구현
- [x] 비밀번호 글자수 확인 구현
- [x] 핸드폰, 생년월일에 숫자만 입력가능하게 하기
- [x] 회원가입 시 unique id 생성
- [x] 입력한 값을 data.json, local storage에 저장
- [x] 핸드폰 인증번호 보내기 누르면 팝업으로 띄워주기
- [x] 약관 동의 전체 선택하기 누르면 전체 선택되게 하기

## 기타

 validation을 어떻게 보여줄지는 좀더 고민해야 할 듯

랜덤 문자열을 생성하게 했으나 데이터가 없어서 중복됐을 때 함수 다시 실행하게 하는 걸 구현해야 함
