### ISSUE TITLE
✅ [23.02.07] header 작업

### ISSUE THREAD

**Issue by Stilllee** [phoenix-kurly/phoenix-kurly#61]
## 작업 사항
23.06.07 pull request 충돌을 기점으로 이를 해결하고 추가 기능 및 관련 스타일 작업 진행

## Todo
- [x] pr 충돌해결
- [ ] header 상단메뉴(네비) 변경되는 스타일 작업
- [ ] 카테고리 이미지 삽입 및 스타일 조정
- [ ] page switch(마켓칼리, 뷰티칼리) js
- [x] 특정 아이콘 링크연결 구상
- [x] top-banner 닫기동작 구현
