### ISSUE TITLE
✅ [23.02.07] 메인페이지 자바스크립트

### ISSUE THREAD

**Issue by baeseongjae** [phoenix-kurly/phoenix-kurly#64]
## 작업 사항
메인 페이지 자바스크립트 활용하여 각각의 기능 구현

## Todo
- [ ] 메인 영역 상품리스트 슬라이드 기능 구현 (Swiper)
- [ ] 장바구니 모달창 js 구현
- [ ] 장바구니 담기 구현
- [ ] 최근 본 상품 js 구현 (localstorage활용)
