### ISSUE TITLE
✅ [23.02.07] 제품 상세페이지 작업

### ISSUE THREAD

**Issue by yurimpark** [phoenix-kurly/phoenix-kurly#68]
## 작업 사항
> 작업 사항(구현할 내용)을 입력해주세요.
✅ 완료된 작업 사항은 제목에 완료한 이슈 번호를 입력해주세요.

## Todo
- [x] 리뷰쓰기 누르면 뜰 팝업 css 작업
- [x] 제품상세페이지 찜버튼 토글
- [x] navbar is-active 클래스 탈부착

## 기타
모듈 css 수정
스더님 헤더와 보경님 장바구니 버블 코드를 가져와서 사용하였습니다!
