### ISSUE TITLE
✅ [23.02.08] 회원가입 기능 구현

### ISSUE THREAD

**Issue by hungerbk** [phoenix-kurly/phoenix-kurly#82]
## 작업 사항
회원가입 기능 구현

## Todo
- [x] 이메일, 비밀번호 유효한 경우에만 회원가입 가능
- [x] 회원가입 완료 후 메인페이지로 이동
- [x] 유니크 키 중복 금지 검사
- [x] 서버에 회원가입 폼 전송
- [x] data.json 재설정

## 기타
> 필요한 경우 작성해주세요.
