### ISSUE TITLE
✅ [23.02.09] 제품 상세페이지 작업

### ISSUE THREAD

**Issue by yurimpark** [phoenix-kurly/phoenix-kurly#93]
## 작업 사항
> 작업 사항(구현할 내용)을 입력해주세요.
✅ 완료된 작업 사항은 제목에 완료한 이슈 번호를 입력해주세요.

## Todo
- [ ]  navbar sticky 안먹힘 해결하기
- [ ] 장바구니 넣기 버튼 누르면 버블 4초 띄우기
- [ ] 제품 수량 버튼 작동
- [ ] 이미지 연결 안된거 고치기
- [ ] 상세페이지 일범님 작업한거 합치기
- [ ] 후기작성 버튼 누르면 후기쓰기 창 띄우기
- [ ] 문의하기 창 후기작성 창 재활용해서 만들기
- [ ] 문의하기 버튼 누르면 문의 창 띄우기

## 기타
> 필요한 경우 작성해주세요.
